name: Patch IPA

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 🔥 Download IPA from GitHub Releases (YOUR LINK)
      - name: Download IPA
        run: |
          wget https://github.com/hamalainenmiska100-hue/ProjectEarthiOSPatcher/releases/download/V1/ipa.ipa -O ipa.ipa
          echo "[INFO] File downloaded:"
          ls -lh ipa.ipa

      # 🔧 Run patcher
      - name: Run patcher
        run: python main.py

      # 📦 Upload patched IPA
      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: patched.ipa
