name: Patch IPA

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 🔥 RELIABLE GOOGLE DRIVE DOWNLOAD
      - name: Download IPA
        run: |
          FILE_ID="14CpIdYbJ1eSmFe253XGqLM_tg0nNKHxQ"

          echo "[INFO] Getting confirm token..."

          curl -c cookies.txt -L "https://drive.google.com/uc?export=download&id=$FILE_ID" > response.html

          CONFIRM=$(grep -o 'confirm=[0-9A-Za-z_]*' response.html | head -n1 | cut -d= -f2)

          echo "[INFO] Confirm token: $CONFIRM"

          echo "[INFO] Downloading real file..."

          curl -Lb cookies.txt "https://drive.google.com/uc?export=download&confirm=$CONFIRM&id=$FILE_ID" -o ipa.ipa

          echo "[INFO] Download finished"

          ls -lh ipa.ipa

      - name: Run patcher
        run: python main.py

      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: patched.ipa
